#!/usr/bin/env python3
"""Generates the seed INSERT for public.duplicate_candidates from the three
high-confidence report files (05b, 05c, 05d output). High tier only, for
now — medium/low stay purely in the report files, untouched, per the same
"keep them separate" instruction as the original nsdi<->dmrca-only design.

Survivor/redundant assignment per check:
  cross_source          — survivor = the already-reviewed record (has real
                           coordinates); redundant = the standalone,
                           never-reviewed record from the report.
  unclaimed_vs_verified — survivor = the already-verified record; redundant
                           = the unclaimed one (retiring it is the point).
  intra_reviewed        — both sides are reviewed; survivor picked by
                           source-type priority nsdi > dmrca > osm (nsdi
                           rows tend to already carry the richest source
                           sets, being this pipeline's original ground-
                           truth layer), tie-broken by id for determinism.

Writes report/duplicate-candidates-seed.sql — reviewed by hand before
running against the real project, not auto-applied by this script.
"""
from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "report" / "duplicate-candidates-seed.sql"

SOURCE_PRIORITY = {"nsdi": 0, "dmrca": 1, "osm": 2}


def prefix(mosque_id: str) -> str:
    return mosque_id.split("-", 1)[0]


def sql_str(v) -> str:
    if v is None:
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    master = {r["id"]: r for r in json.loads((BASE / "master" / "output" / "master-dataset.json").read_text())}

    rows = []  # (check_type, survivor, redundant, score, tier, distance_m)

    # --- Check A: cross_source ---
    a = json.loads((BASE / "report" / "reviewed-dmrca-overlap-candidates.json").read_text())
    for r in a:
        if r["matchConfidence"] != "high":
            continue
        redundant_id = next((rec["id"] for rec in master.values() if rec.get("dmrcaRegistrationNo") == r["dmrcaRegistrationNo"]), None)
        if not redundant_id:
            print(f"WARN: could not resolve dmrca id for {r['dmrcaRegistrationNo']!r}, skipping")
            continue
        rows.append(("cross_source", r["mosqueRecordId"], redundant_id, r["matchScore"], "high", None))

    # --- Check B: intra_reviewed ---
    b = json.loads((BASE / "report" / "intra-reviewed-duplicate-candidates.json").read_text())
    for r in b:
        if r["tier"] != "high":
            continue
        ida, idb = r["idA"], r["idB"]
        pa, pb = SOURCE_PRIORITY.get(prefix(ida), 9), SOURCE_PRIORITY.get(prefix(idb), 9)
        if pa < pb or (pa == pb and ida < idb):
            survivor, redundant = ida, idb
        else:
            survivor, redundant = idb, ida
        rows.append(("intra_reviewed", survivor, redundant, r["nameScore"], "high", r["distanceM"]))

    # --- Check C: unclaimed_vs_verified ---
    c = json.loads((BASE / "report" / "unclaimed-vs-verified-duplicate-candidates.json").read_text())
    for r in c:
        if r["tier"] != "high":
            continue
        rows.append(("unclaimed_vs_verified", r["verifiedMosqueId"], r["unclaimedMosqueId"], r["nameScore"], "high", r["distanceM"]))

    lines = ["-- Auto-generated by scripts/05e_generate_duplicate_seed.py — high tier only.", "begin;", ""]
    for check_type, survivor, redundant, score, tier, dist in rows:
        lines.append(
            "insert into public.duplicate_candidates "
            "(check_type, survivor_mosque_id, redundant_mosque_id, match_score, match_tier, distance_m) "
            f"values ({sql_str(check_type)}, {sql_str(survivor)}, {sql_str(redundant)}, {score}, {sql_str(tier)}, "
            f"{dist if dist is not None else 'null'}) "
            "on conflict (survivor_mosque_id, redundant_mosque_id) do nothing;"
        )
    lines += ["", "commit;"]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"cross_source: {sum(1 for r in rows if r[0]=='cross_source')}")
    print(f"intra_reviewed: {sum(1 for r in rows if r[0]=='intra_reviewed')}")
    print(f"unclaimed_vs_verified: {sum(1 for r in rows if r[0]=='unclaimed_vs_verified')}")
    print(f"Total: {len(rows)}")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
